### ISSUE TITLE
Uncaught Invalid provider - only instances of Provider and Type are allowed

### ISSUE THREAD

**Issue by allanmagale** [HackedByChinese/ng2-idle#10]
After applying gulp-webpack to my ts scripts, running my application gets this error in Chrome:

> Uncaught Invalid provider - only instances of Provider and Type are allowed, got: [object Object]

When I remove the IDLE_PROVIDERS from the bootstrap method it works fine.

Environment:
Angular2: RC1
ng2-idle: 1.0.0-alpha.12

**Comment by Works4sure** [comment]
+1

I get the same error, running Webpack. Hopefully this can be fixed, since there isn't really an alternative to ng2-idle for Angular 2.

**Comment by HackedByChinese** [comment]
I honestly don't know what the deal is (this is the same as #3). It works in other setups, but I can't seem to get this working in Webpack. I don't have much experience with WP, so I could use some help.

**Comment by smorks** [comment]
We are using webpack in our project as well, and I believe that the changes that were merged for Angular 2 RC5 support should fix this issue.

**Comment by stephengeorgewest** [comment]
This specific bit seems to be working in RC6, but I couldn't get past the extra issue mentioned in #3
