### ISSUE TITLE
Switch to Angular 2.0.0 and webpack

### ISSUE THREAD

**Issue by isametal88** [HackedByChinese/ng2-idle#18]
Hi guys,

I'm quite new to this environment, I'm sorry if I'll say something stupid, but I really need your help.

I was using your component in a previous version (in development stage) of my application, using SystemJs and Angular RC-6, and all seemed to work properly.
With the release of Angular 2 Final, I started a new project from scratch, switching to webpack (that I still can't figure out :-( )
I added IDLE_PROVIDERS to the providers of my module, like the previous version, but the application is asking me (and it wasn't before) to configure KeepAliveSvc in the providers. I have no need to use the keep-alive function of your component, I only need to manage the idle behaviour.

Tell me whatever you need

Thank you very much

Isaia

**Comment by isametal88** [comment]
[https://github.com/HackedByChinese/ng2-idle/issues/17](url)

This workaround worked for me, but obviously a more solid approach would be much better :-)

**Comment by HackedByChinese** [comment]
fa7441157b23574219dbfa098f15d42d57abd5c6 Brings it up to 2.0.0
