### ISSUE TITLE
Switch to Angular 2.0.0

### ISSUE THREAD

**Issue by tiagocpeixoto** [HackedByChinese/ng2-idle#19]
Hi everyone,

After upgraded my project to Angular 2.0.0, I can´t use browserify to generate bundle.js because ng2-idle throws "no provider for Http!" exception when I try to load my app from the browser (as I said, using bundle.js generated by browserify).

If I remove ng2-idle dependency from my components, I don´t get this exception and the app works flawlessly.

So, I suppose that ng2-idle should be switched to Angular 2.0.0. Is this statement correct?

Is there anything that I can do to overcome this problem?

Thanks in advance.

Tiago Peixoto.

**Comment by isametal88** [comment]
https://github.com/HackedByChinese/ng2-idle/issues/17

This workaround worked for me , too. But obviously we are waiting for an update of the component :-)

**Comment by HackedByChinese** [comment]
fa7441157b23574219dbfa098f15d42d57abd5c6 Brings it up to 2.0.0
