### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by david-gang** [HackedByChinese/ng2-idle#2]
Hi,

It would be great to have a code snippet to see how to use the Idle service.

Thanks,
David

**Comment by HackedByChinese** [comment]
Indeed, sorry. I was a little gunshy about putting one together with Angular state being in a beta flux.
Oddly enough, there is an example in the [README](https://github.com/HackedByChinese/ng2-idle-keepalive#getting-started) for the ng2-idle-keepalive plugin for ng2-idle. I'll refresh with the latest Angular beta and add a sample.

**Comment by paullryan** [comment]
So on that note, what am I doing wrong with 

```js
      idle.setIdle(5);
      idle.setTimeout(5);
      idle.setInterrupts(DEFAULT_INTERRUPTSOURCES);
      idle.onIdleStart.subscribe(response => {
        console.log('idling');
        console.log(response);
      });
      idle.onIdleEnd.subscribe(response => {
        console.log('idle ended');
        console.log(response);
      });
      idle.onTimeout.subscribe(response => {
        console.log('timed out');
      });
```

seems like the correct direction based on your source but none of my subscribes are triggering. If I figure it out before you get back on I'll try to update here.

**Comment by BahKoo** [comment]
I think you need to call idle.watch() to get it started.

**Comment by PriyankaKadam001** [comment]
Hi, I need step by step tutorial for ng2-idle or relevant example? Please share example links.

**Comment by PriyankaKadam001** [comment]
I need to use ng2-idle in my app and I have created one service which will handle session handling when user is idle and trying to access that service in my app but it is not working but same thing if I will write in component it works fine. Please share tha link if you have any examples.
