### ISSUE TITLE
Unexpected value '[object Object]' imported by the module 'AppModule', - ionic 2

### ISSUE THREAD

**Issue by herbzi** [HackedByChinese/ng2-idle#25]
Hi, I'm on alpha 18 I just created a new ionic 2 project with 

ionic start myApp --v2.

Then all I did was install via npm and include the module in my module's imports as in the ng2-idle-example repo.

I get this error and I cannot figure out why.

**Comment by herbzi** [comment]
Ok, I guess it's just that ng2-idle forces angular version 2.0.0 . I created a fork with "^2.0.0" for the angular dependencies and installed that instead so it uses the same angular code that i'm using. Then everything works fine.

**Comment by gminky019** [comment]
I'm having the same problem. I don't really want to downgrade to a lower version for the angular dependencies. Any other ideas?

**Comment by rjlee7** [comment]
@herbzi I tried the same thing with forking in order to up to 2.1.0 but getting the `Can't resolve 'ng2-idle' in '/Users/hedgeable/Documents/web-new/src/app'` error. Any sugestions?

**Comment by rjlee7** [comment]
@herbzi I tried the same thing with forking in order to up to 2.1.0 but getting the Can't resolve 'ng2-idle' in '...../src/app' error. Any sugestions?

**Comment by herbzi** [comment]
Basically all i did was copy node-modules/ng2-idle into a another local folder, changed the angular dependencies in it to "^2.0.0" and installed from that local folder. There's probably a much better way to do it , idk. Don't just fork/clone this repo though, because by default it doesn't include the dist folder which is what npm installs. (unless you want to build it yourself).

**Comment by HackedByChinese** [comment]
Ng-Idle has been significantly refactored. It includes a relaxation on the Angular dependencies. Please refer to the README and CHANGELOG on how to update your application.
