### ISSUE TITLE
Add AOT support

### ISSUE THREAD

**Issue by herbzi** [HackedByChinese/ng2-idle#26]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**Current behavior**
If I include ng2-idle in my import modules while doing AOT compile I get the following error:
 
 [11:54:02]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda...

If I take out the ng2-idle import etc, it works fine. 

Related to: https://github.com/angular/angular/issues/11262

Does ng2-idle have support for AoT compilation? I don't see any .metadata.json files.

**Please tell us about your environment:**
Running with ionic 2, windows 10. typescript. 

* **@ng-idle version:** 2.0.0-beta.2

* **Angular version:** 2.1.1

**Comment by HackedByChinese** [comment]
Sorry, I still haven't gotten the hang of AOT yet. I'll try and get this in beta.3.

**Comment by HackedByChinese** [comment]
OK, beta.3 is out. I'm now using `ngc` to compile the dist JS and includes metadata.

**Comment by dbrunner82** [comment]
The beta.3 release doesn't appear to be available on npm. Can you please update the available releases on npm?

**Comment by HackedByChinese** [comment]
beta.3 was pushed and we're already up to beta.4

**Comment by pacchy** [comment]
Can't get beta.3 on npm yet.
