### ISSUE TITLE
Custom Expiry not functioning as expected

### ISSUE THREAD

**Issue by markmaynard** [HackedByChinese/ng2-idle#27]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**Current behavior**
Created a cookie based IdleExpiry that stores lastValue as a cookie. Activity in one tab does not prevent timeout in another tab.
I was able to get something close to what I wanted by modifying the toggleState method in Idle and inserting the following at the top of the function:
`if (!this.expiry.isExpired()) {
          return;
        }
`

This checks the cookie and prevents expiration.

**Expected behavior**
Activity in one tab prevents timeout in all tabs.

**Minimal reproduction of the problem with instructions**
Replace SimpleExpiry with the following class
`@Injectable()
export class CookieExpiry extends IdleExpiry {
  private lastValue: Date = undefined;

  constructor(
      private cookieService: CookieService
  ) {
    super();
  }

  /*
   * Gets or sets the last expiry date.
   * @param value - The expiry value to set; omit to only return the value.
   * @return The current expiry value.
   */
  last(value?: Date): Date {
    if (value !== void 0 && value !== undefined) {
      this.lastValue = value;
      let expireDate = new Date(new Date().setFullYear(new Date().getFullYear() + 1));
      this.cookieService.put('idle-timeout', this.lastValue.toUTCString(), { expires: expireDate} );
    } else {
      if (this.cookieService.get('idle-timeout') !== undefined) {
        this.lastValue = new Date(this.cookieService.get('idle-timeout'));
      } else {
        this.lastValue = undefined;
      }
    }
    return this.lastValue;
  }

  /*
   * Returns whether or not it is expired.
   * @return True if expired; otherwise, false.
   */
  isExpired(): boolean {
    let expiry = this.last();
    return expiry !== undefined && expiry <= this.now();
  }
}
`
Open app on two tabs, move mouse to trigger activity on one tab while allowing other tab to remain inactive.

**What is the motivation / use case for changing the behavior?**
Allow activity on one tab to keep other tabs from expiring. Since all tabs are using the same session cookie the "out-of-focus" tab is expiring session for all tabs.

**Please tell us about your environment:**
Ubuntu 16.04
NPM
Webpack-dev server

* **@ng-idle version:** 2.x
"@ng-idle/core": "^2.0.0-beta.4"

* **Angular version:** 2.x
"@angular/core": "2.1.2"

* **Browser:** 
ALL

* **Language:**
ALL

* **Node:** `node --version` =
v5.12.0

**Comment by markmaynard** [comment]
Sorry to bug you but I see responses on other issues, is there something my issue is missing?

**Comment by HackedByChinese** [comment]
@markmaynard Sorry, I've been busy at work and haven't had time to reproduce the issue. If you think you've got a handle on what needs to change to get it working, feel free to submit a pull request. I might be able to take a look this weekend.

**Comment by markmaynard** [comment]
I thought I had a fix but I was incorrect. The problem seems to be that activity sets a new timeout time in my cookie, but none of the other tabs actually check the cookie to see that this timeout has been extended. What I _think_ need to happen is that when a timeout occurs on a tab, it first checks the cookie(or other shared storage) to see if is time is greater than the time in the cookie. If not it sets a new timer for the difference between stored_time and now.

**Comment by HackedByChinese** [comment]
Ah, right. So, evergreen browsers (except Edge) support an `onChanged` event for cookies. That would be ideal (and most analogous to how I handle it via storage in the original `ng-idle`. However, we'd still need a way to handle browsers that don't support this. It may make sense to create a custom interrupt source that triggers a function at intervals (say, 1 second) to see if the cookie value has changed. If it has, trigger the interrupt. This, in concert with your CookieExpiry should handle activity from other tabs.

**Comment by rousseaufiliong** [comment]
If localStorage is an option for you, a new release of ng2-idle has been made last week on tag [v2.0.0-beta.6](https://github.com/HackedByChinese/ng2-idle/tree/v2.0.0-beta.6).

**Comment by markmaynard** [comment]
I have a cookie storage version that works fine in that it is a centralized store for the timeout value. The problem I ran into is that the idle timeout is set by all the open tabs but the interval in the watch function does not check the the updated values. The change I PRed should fix that.

**Comment by Splaktar** [comment]
https://github.com/HackedByChinese/ng2-idle/pull/37 was merged. Should this issue be closed now?

**Comment by markmaynard** [comment]
Yes, sorry, closing now.
