### ISSUE TITLE
Latest beta versions not included in npm

### ISSUE THREAD

**Issue by harleyb16** [HackedByChinese/ng2-idle#29]
We are attempting to update to the latest version of angular (2.3.0) using npm. In this, we recieved an error for your old ng2-idle-keepalive project.
![image](https://cloud.githubusercontent.com/assets/11000810/21200763/adb3d83e-c205-11e6-8d04-62cb0208346a.png)

After noticing you had merged the project into ng2-idle, we updated our package.json to request version 2.0.0-beta.4. It seems the latest packages haven't been published 
![image](https://cloud.githubusercontent.com/assets/11000810/21200828/ee371eb6-c205-11e6-93d1-9b7148d95b3b.png)

Are you still supporting npm packages?
https://www.npmjs.com/package/ng2-idle

**Comment by HackedByChinese** [comment]
Hello. `ng2-idle` and `ng2-idle-keepalive` have been deprecated (you should be getting a warning in NPM). They have been reorganized and published as `@ng-idle/core` and `@ng-idle/keepalive`. You can refer to the [example](https://hackedbychinese.github.io/ng2-idle/) to see how to use these packages.
