### ISSUE TITLE
onTimeout event not triggered on the "onResume" event Cordova / Ionic 2

### ISSUE THREAD

**Issue by dnmd** [HackedByChinese/ng2-idle#46]
**I'm submitting a ...**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ - ] feature request
[ - ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**Current behavior**
There are three ways to send an app to the "background" (in general). Only in the first scenario, where the hardware button is pushed, the onTimeout event is triggered correctly.

[ x ] Using the home button; _works correctly_
[ - ] Switching to another app (double tap home button / switch app button); _not working_
[ - ] Turning the screen off (clicking the off button shortly); _not working_

**Expected behavior**
- Peform the "check" on "all" the resume events / three scenario's above. Or (if that doesn't already happen);
- Trigger the "check" on a defined event (or be able to define an event on which it needs to be checked), like "resume"
- Being able to manually trigger the "check" wheter the users' state is idle. e.g. add some logic to the Cordova / Ionic 2 app, bind to the "resume" event and do something like: this.idle.isIdle() => and act on it.

**Minimal reproduction of the problem with instructions**
Send an Cordova / Ionic 2 app to the background via either the second or third method.

**Please tell us about your environment:**

* **@ng-idle version:** 2.@latest

* **Ionic version:** 2.@latest

* **Language:** [ TypeScript@latest ]

**Comment by HackedByChinese** [comment]
I haven't used Cordova or Iconic before, so I'll need an assist on this. However, `DEFAULT_INTERRUPTSOURCES` is defined as [this](https://github.com/HackedByChinese/ng2-idle/blob/master/modules/core/index.ts#L17-L18). So if you are using this, it's only looking for typical touch, mouse, and keyboard events on the document, plus storage events.

You can definitely use your own settings for interrupt sources and even create and use your own. I'm taking a shot in the dark here, but by using what's defined in `DEFAULT_INTERRUPTSOURCES` plus adding `new WindowInterruptSource('focus refresh')` (or whatever makes sense in Iconic), you can listen for those events on the window when the app comes back from the background.

**Comment by dnmd** [comment]
Thanks, and sorry for the late reply. After a good closer look, it seemed that the plugin was working just fine. The issue was caused due to a prompt which was presented to the user, but - with the app in the background - was unable to load.
