### ISSUE TITLE
Type Error: Cannot read property 'getTime' of null

### ISSUE THREAD

**Issue by MarbleDaemon** [HackedByChinese/ng2-idle#54]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**Current behavior**

When Idle start: onIdleStart:

core.es5.js:1084 ERROR TypeError: Cannot read property 'getTime' of null
    at watchFn (idle.js:202)
    at ZoneDelegate.webpackJsonp.1271.ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:4140)
    at ZoneDelegate.webpackJsonp.1271.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.webpackJsonp.1271.Zone.runTask (zone.js:191)
    at ZoneTask.invoke (zone.js:486)
    at timer (zone.js:1512)

**Expected behavior**

Subscription to onIdleStart should be triggered.

**Minimal reproduction of the problem with instructions**

This is the method used in AppComponent
```
constructor(private idle: Idle) {
   this.setupIdle();
}

 private setupIdle() {
    this.idle.setIdle(20);

    this.idle.onIdleStart.subscribe(() => {
        ....
    });

    this.resetIdle();
  }

private resetIdle() {
    this.idle.watch(true);
  }
```
**What is the motivation / use case for changing the behavior?**

Auto logout when user idle

**Please tell us about your environment:**

Windows 10, IntelliJ IDEA, NPM, Node.js

* **@ng-idle version:** 2.x

"@ng-idle/core": "^2.0.0-beta.11"

* **Angular version:** 2.x

"@angular/core": "^4.1.1"

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 58.0.3029.110

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node:** `node --version` =
v6.10.3

**Comment by HackedByChinese** [comment]
Thanks, this is fixed in beta.12
