### ISSUE TITLE
interrupt from modal ok button

### ISSUE THREAD

**Issue by faisalloe** [HackedByChinese/ng2-idle#59]
Angular4 with @ng2-idle trying to capture the inactivity of the user.

code example link
https://hackedbychinese.github.io/ng2-idle/

I am trying to customize it so every time user goes idle i show modal with ok button. and user will able to resume only ok is clicked on the modal.

on page load default interrupts are on

    idle.setInterrupts(DEFAULT_INTERRUPTSOURCES); 

on `idleStart` i show my modal and count down begins
on `onIdleEnd` i close my modal

when modal is open i want to disable `DEFAULT_INTERRUPTSOURCES` only manual interrupt so i called `idle.clearInterrupts()` and on modal ok press event calling `idle.interrupt(true);` 
once modal is close i set `idle.setInterrupts(DEFAULT_INTERRUPTSOURCES);` again.

does not seems to work very well. after modal close and open again it does not car about `DEFAULT_INTERRUPTSOURCES` and on `setIdle` time it goes automiticaly `idle` mode even though user interacts with the UI.

**Comment by HackedByChinese** [comment]
When configuring idle, use `AutoResume.notIdle`. This will allow user activity to reset the idle timer as long as they are NOT idle, which means that when they _do_ go idle, you have to reset the idle service manually when they click OK as you requested.

You don't need to do anything extra, like modify or pause the interrupt sources. From the demo you linked, simply import the `AutoResume` enum and add the following line to the AppComponent constructor (or your equivalent):

```
idle.setAutoResume(AutoResume.notIdle);
```

Then in your OK button click handler, just call `idle.watch()`.

**Comment by faisalloe** [comment]
awesome, great help appreciated.
