### ISSUE TITLE
Any intention to upgrade de angular 5?

### ISSUE THREAD

**Issue by druidamix** [HackedByChinese/ng2-idle#68]
Hello,

Time since last commit. Will be the code upgraded to angular 5?

Thanks.

**Comment by patrickracicot** [comment]
@druidamix  Do you get any errors when compiling?  I've just created a sandbox project with angular-cli on the latest version (v5), and everything seems to be working.

**Comment by druidamix** [comment]
Sorry i didn't explain .
I upgraded http to httpclient since is deprecated. Then removed http from package.json to save size on dist.
So, building: 
node_modules/@ng-idle/keepalive/src/keepalive.d.ts(2,41): error TS2307: Cannot find module '@angular/http'.

Adding http work perfectly.

Well, seems happens with others packages.

**Comment by IEvangelist** [comment]
Is there a potential ETA on this one? This just so happens to be one of the last dependencies that I have that hasn't upgraded yet. Would you like a PR for the changes?

**Comment by HackedByChinese** [comment]
Bear with me, I've not kept up with Angular much recently. Yes, I surely want to support Angular 5. However, I really don't feel like releasing versions for 2/4 and 5+. 

Is it reasonable to just target the most recent release are people tending to orbit around a specific release like they did with AngularJS minor releases?

**Comment by HackedByChinese** [comment]
Ugh, I see... They're adopting a Stable/LTS model. I mean, makes sense for them. Sucks for one guy with a little module.

**Comment by alexrosano** [comment]
I think latest release is fine.  @IEvangelist can you post a PR?  I can help test and possibly contribute.

**Comment by HackedByChinese** [comment]
I mean, it does make some sense to have my own stable/LTS in regards to the versions of Angular they target, but it does feel dirty tying LTS/stable to that of a dependency. The other problem is I'm still technically in prerelease state.

I could take master and turn that into the 2.0 release candidate with the intention of that becoming my LTS, targeting angular 4 (2 appears to be no longer supported). I can then create a new branch for 3.0 beta with the intention of that becoming my stable (supporting angular 5). Then we can go from there. Master then becomes version next.

**Comment by AHelper** [comment]
I'm working on a PR for both #69 and this.  I can't keep Angular 2 support as @angular/common/http didn't exist, but I can support 4 & 5. Only thing blocking me now is that the `ngc:es5/es6` steps don't output to the same path. 4 uses `.tmp/es5/core`, etc. with 5 using `.tmp/es5/modules/core`, etc.. I'm guessing there's a TS change wrt. outputs that I'm not aware of.  I'll try pushing the branch to my repo tonight and take another stab at it.

**Comment by HackedByChinese** [comment]
OK, thanks. Sounds like we can just drop support for 2, and we'll kick the can for breaking changes in angular versions down the road.

**Comment by HackedByChinese** [comment]
Closed by #72
