### ISSUE TITLE
Please fix the deprecated @angular/http

### ISSUE THREAD

**Issue by einewton** [HackedByChinese/ng2-idle#69]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**What is the motivation / use case for changing the behavior?**
Please view the angular teams [pull req](https://github.com/angular/angular/pull/18906) saying that as of Angular 4.3 angular/http is **deprecated**.

* **Angular version:** 4.4.6

I have removed angular/http in favor of angular/common/http from my project but now your module will not load.

_ERROR in ..../node_modules/ng-idle/keepalive/src/keepalive.d.ts (2,41): Cannot find module 'angular/http'._

**Comment by patrickracicot** [comment]
Related to #68

**Comment by HackedByChinese** [comment]
beta 13 now uses angular 4+, which gets rid of angular/http.

**Comment by mmeester** [comment]
I'm still getting the `Cannot find module '@angular/common/http'` error

**Comment by strypeez** [comment]
Recently installed ngIdle and I am getting the Cannot find module @angular/common/http error
