### ISSUE TITLE
support for angular 2.0.0-rc.0 and later

### ISSUE THREAD

**Issue by BahKoo** [HackedByChinese/ng2-idle#7]
With the release of **angular 2.0.0-rc.0** all of the angular packages have been renamed. This causes problems with ng2-idle.

**Comment by HackedByChinese** [comment]
I will upgrade angular to RC over the weekend.

**Comment by BahKoo** [comment]
You're the best. Thanks!

**Comment by HackedByChinese** [comment]
alpha.11 updated to rc.1
