### ISSUE TITLE
Timeout countdown should be shown in minutes and seconds.

### ISSUE THREAD

**Issue by arpit03187** [HackedByChinese/ng2-idle#75]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**Current behavior**
The timeout warning configuration currently only supports seconds as a unit.

**Expected behavior**
The timeout warning configuration should allow minutes and seconds to show up in the warning.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

If the timeout configuration is done for let's say 2 minutes the countdown should start initially as 1 minute 59 seconds and keep going down instead of showing 120 seconds.

**Please tell us about your environment:**

Windows 7

* **@ng-idle version:** 2.x

ng-idle/core: ^2.0.0-beta.12,
ng-idle/keepalive: ^2.0.0-beta.12,

* **Angular version:** 2.x

Angular version - 4.4.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.2.0

* **Node:** `node --version` = 6.11.4

**Comment by HackedByChinese** [comment]
I intentionally avoided making decisions on how the time is formatted, since that has localization implications. You'll need to do the formatting of the remaining seconds yourself in your event handler.
