### ISSUE TITLE
Gives error for@angular/common/http in keepalive.d.ts class

### ISSUE THREAD

**Issue by NehaPandyaji** [HackedByChinese/ng2-idle#84]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **@ng-idle version:** 2.x

* **Angular version:** 2.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node:** `node --version` =

**Comment by HackedByChinese** [comment]
Angular 2 is no longer supported as of beta.13 (see https://github.com/HackedByChinese/ng2-idle/blob/master/CHANGELOG.md). Angular 2 isn't even supported by Angular anymore.
