### ISSUE TITLE
import 'zone.js' which may cause duplicate

### ISSUE THREAD

**Issue by vincent-cm** [HackedByChinese/ng2-idle#99]
After installing the 6.0.0-beta.1
The AoT build will throw an error at runtime:

`Uncaught Error: Zone already loaded.`

As ./modules/core/src/interruptsource.ts has zone.js imported which I think it is not necessary

**Comment by sherlock1982** [comment]
Well Zone should be loaded prior Angular. So every user should do it for himself before. IMHO no other components should reference Zone directly.

**Comment by richie50** [comment]
@vincent-cm when i comment out zone js from my package.json my app doesn't load at all. I get zone js cannot be found. Did you experience that?

**Comment by vincent-cm** [comment]
@richie50 I mean the source code from ./node_modules/ng2-idle/, recommend you try to download the ng2-idle source and insert into your own project.

**Comment by richie50** [comment]
@vincent-cm thanks will do 👍

**Comment by jtcrowson** [comment]
Appreciate the workaround, but of course, don't want to commit my node_modules to source control.  @HackedByChinese is this workaround in consideration for implementation?

**Comment by sherlock1982** [comment]
I used patch-package for it. It's amazing for doing small patches in published libs.

**Comment by jtcrowson** [comment]
Good call @sherlock1982. Thanks!!

**Comment by richie50** [comment]
@sherlock1982 @jtcrowson @HackedByChinese @vincent-cm i have a fix. i will be submitting a pull request soon. Works with angular 5.0.3
